- apis/v1alpha1/gameserverset_types.go
- config/crd/bases/game.kruise.io_gameserversets.yaml
- pkg/controllers/gameserverset/gameserverset_manager.go
Add ObservedGeneration to GameServerSet.
1. Update api types and crd.
2. Add status update logic.
> Feat: add ObservedGeneration to GameServerSet

- pkg/controllers/gameserverset/gameserverset_controller.go
- pkg/controllers/gameserverset/gameserverset_manager.go
When the template metadata is not empty, the label of game.kruise.io/owner-gss will be added to the gss, which will result in an inconsistency with the previous judgment when getting the hash.
Use DeepCopy when gss is passed in as a parameter
> fix: gss status sync failed when template metadata is not null

- pkg/controllers/gameserverset/gameserverset_manager.go
- pkg/controllers/gameserverset/gameserverset_manager_test.go
- pkg/util/math.go
- pkg/util/math_test.go
panic(runtime error: slice bounds out of range [:6] with capacity 5) occurs when:
gss with
- replicas: 5 -> 1
- reserveIds: 0, 4, 5 -> 0
- gs index list: 1, 2, 3, 6, 7
Added marginal conditions - only those remove-reserved GameServers will be added back when there is a need for capacity expansion
> fix: add marginal conditions to avoid fatal errors

- pkg/util/gameserver.go
Background:
https://github.com/openkruise/kruise-game/issues/50
> feat: add default serviceName for asts

- Makefile
- apis/v1alpha1/gameserverset_types.go
- config/crd/bases/game.kruise.io_gameserversets.yaml
- docs/en/user_manuals/CRD_field_description.md
- docs/中文/用户手册/CRD字段说明.md
- pkg/controllers/gameserverset/gameserverset_manager.go
- pkg/controllers/gameserverset/gameserverset_manager_test.go
Sometimes, we need to scale down the game servers and no longer create those automatically until those game servers are manually specified to be recreated. 
The ScaleDownStrategyType field is added to the scale strategy. When the ScaleDownStrategyType is ReserveIds, the ID of the scaled down game server will be backfilled in the reserveGameServerIds field. When the user wants to recreate it, remove the ID from the reserveGameServerIds field and increase the replicas, which can meet the above requirements.
> feat: add ReserveIds ScaleDownStrategyType

- pkg/util/slice.go
- pkg/util/slice_test.go
Slice is nil and slice does not exist elements, both are considered to be the same, which can help to avoid format problems when the user enters.
> assume that slices without elements are equal

- apis/v1alpha1/gameserver_types.go
- docs/en/getting_started/gameservers_scale.md
- docs/中文/快速开始/游戏服水平伸缩.md
- pkg/util/gameserver.go
- pkg/util/gameserver_test.go
https://github.com/openkruise/kruise-game/issues/84
Allocated opsState means the gs is already allocated by kruise-game-open-match-director, players is ready / already in the gs, so that gs with Allocated opsState should not be deleted easily.
After adding Allocated opsState, the deletion priority of opsState has changed. Scale-down the game servers for which the opsState values are WaitToBeDeleted, None, Allocated, and Maintaining in sequence.
> feat: add new opsState named Allocated

- apis/v1alpha1/gameserver_types.go
- config/crd/bases/game.kruise.io_gameservers.yaml
- config/crd/bases/game.kruise.io_gameserversets.yaml
- pkg/controllers/gameserver/gameserver_manager.go
- pkg/controllers/gameserver/gameserver_manager_test.go
https://github.com/openkruise/kruise-game/issues/116
> ServiceQuality supports multiple results returned by one probe

- apis/v1alpha1/gameserverset_types.go
- config/crd/bases/game.kruise.io_gameserversets.yaml
- docs/en/user_manuals/CRD_field_description.md
- docs/中文/用户手册/CRD字段说明.md
- pkg/controllers/gameserver/gameserver_controller.go
- pkg/controllers/gameserverset/gameserverset_controller.go
- pkg/controllers/gameserverset/gameserverset_manager.go
- pkg/controllers/gameserverset/gameserverset_manager_test.go
- pkg/util/gameserver.go
- pkg/util/gameserver_test.go
- test/e2e/framework/framework.go
- test/e2e/testcase/testcase.go
https://github.com/openkruise/kruise-game/issues/103
https://github.com/openkruise/kruise-game/issues/110
> feat: user-defined GameServers' lifecycle

- cloudprovider/config.go
- cloudprovider/manager/provider_manager.go
- cloudprovider/options/volcenginecloud_options.go
- cloudprovider/volcengine/README.md
- cloudprovider/volcengine/README.zh_CN.md
- cloudprovider/volcengine/clb.go
- cloudprovider/volcengine/clb_test.go
- cloudprovider/volcengine/volcengine.go
- config/manager/config.toml
Add the volcengine provider to open-kruise-game and add the clb plugin.
- Users can declare the required clb id and the corresponding backend pod port in okg's gameserverset resource.
-OKG will automatically help users create corresponding services to implement traffic forwarding
Implementation principle
- Through okg, when creating a service, add clb-related anno to the service; then the cloud-controller-manager component in the vke cluster will recognize the clb anno in the service, create a listener on the clb side, and bind the back-end server group , realize traffic forwarding
Details can be found in the README
> feat(*): add volcengine cloud provider and clb plugin

- cloudprovider/alibabacloud/slb.go
- cloudprovider/kubernetes/hostPort.go
- cloudprovider/kubernetes/ingress.go
- cloudprovider/volcengine/clb.go
- pkg/webhook/mutating_pod.go
- pkg/webhook/webhook.go
https://github.com/openkruise/kruise-game/issues/128
> FailurePolicy of PodMutatingWebhook turn to Fail

- Makefile
- cloudprovider/volcengine/README.md
- cloudprovider/volcengine/README.zh_CN.md
- cloudprovider/volcengine/clb.go
- cloudprovider/volcengine/clb_test.go
When using the volcanoengine clb plugin, the configuration of clb is set through anno, opening this setting is convenient for users;
> enhance: Add annotations config in clb plugin

- cloudprovider/options/volcenginecloud_options.go
- cloudprovider/volcengine/README.md
- cloudprovider/volcengine/README.zh_CN.md
- cloudprovider/volcengine/clb.go
- cloudprovider/volcengine/clb_test.go
1）Add the AllocateLoadBalancerNodePorts parameter in volcengine clb to control whether the generated service is assigned a nodeport port;
2）Release the range restriction of the lb port
> enhance: add AllocateLoadBalancerNodePorts in clb plugin

- cloudprovider/amazonswebservices/README.md
- cloudprovider/amazonswebservices/README.zh_CN.md
- cloudprovider/amazonswebservices/nlb.go
In AWS EKS, the `TargetGroup` should be explicitly specified as the IP type, and the Kubernetes service should avoid using the `aws-load-balancer` annotation to reduce some of the unknown automation logic of the controller. The network model should be fully managed by OKG.
> fix: AmazonWebServices-NLB controller parameter modification

- cloudprovider/alibabacloud/nlb.go
- cloudprovider/alibabacloud/slb.go
- cloudprovider/options/alibabacloud_options.go
- config/manager/config.toml
https://github.com/openkruise/kruise-game/issues/177
> Semantic fixes for network port ranges

- pkg/externalscaler/externalscaler.go
https://github.com/openkruise/kruise-game/issues/188
> feat: add maxAvailable param for external scaler

- cloudprovider/alibabacloud/slb.go
- docs/en/user_manuals/network.md
- docs/中文/用户手册/网络模型.md
Sometime we want map slb UDP and TCP same port to Container ..  More like a "Host"
> alibabacloud slb support map same TCP and UDP port , eg 8000/TCPUDP

- apis/v1alpha1/gameserver_types.go
- pkg/controllers/gameserver/gameserver_manager.go
- 在 GameServer 注解中添加 GameServerOpsStateLastChangedTime 字段
- 当 GameServer 的 OpsState 发生变化时，更新该字段为当前时间 
#199 @chrisliu1995
> feat(GameServer): 添加 OpsState 最后变更时间注解

- apis/v1alpha1/gameserverset_types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/game.kruise.io_gameserversets.yaml
- go.mod
- go.sum
- pkg/controllers/gameserverset/gameserverset_controller_test.go
- pkg/controllers/gameserverset/gameserverset_manager.go
- pkg/controllers/gameserverset/gameserverset_manager_test.go
- pkg/util/gameserver.go
- pkg/util/set.go
- pkg/util/set_test.go
- pkg/util/slice.go
- pkg/util/slice_test.go
- pkg/webhook/validating_gss.go
- test/e2e/framework/framework.go
resolve #203 
Changes `ReserveGameServerIds` to the `[]intstr.IntOrString` type, adapting to the upstream Kruise asts type change to support the range type of ReserveID.
There are some key dependency changes to be aware of, and I'm also trying to remove the unnecessary changes
Key dependency changes：
- kruise-api v1.7.1-> v1.8.0
This PR is still working in progress, and any comments and suggestions are always welcome. Thanks~
TODO:
> feat(GameServerSet): support range type for ReserveIDs

- cloudprovider/volcengine/clb.go
解决如下场景问题：
用户使用了volcengine的clb作为网络选型；新建gss，网络模式未选择fixed，此时会为每个副本依次创建出pod和svc；并且svc上会有pod的ownreference；
此时如果删除某个副本，会将其pod删除，正常情况下svc会连带删除，随后再创出一个pod以及svc；
但是如果旧的svc连带删除比较慢，新的pod已经创出来，旧的svc还没有被删除；此时由于新旧pod的名称一致，需要的svc也名称一致。新的pod就会使用旧的svc；出现问题
解决方案：
在非Fixed模式，给service的注解中打上对应pod的时间戳；则即使旧的svc未删除，新的pod已经创建出来时。也会因为旧的svc带的时旧的时间戳，不会错误的将新的pod和旧的svc绑定上；
> fix:add pod create time in svc

- .github/workflows/e2e-1.26.yaml
- .github/workflows/e2e-1.30.yaml
- config/certmanager/certificate.yaml
- config/certmanager/kustomization.yaml
- config/certmanager/kustomizeconfig.yaml
- config/default/kustomization.yaml
- config/default/manager_webhook_patch.yaml
- config/default/webhookcainjection_patch.yaml
- config/manager/manager.yaml
- config/webhook/kustomizeconfig.yaml
- config/webhook/manifests.yaml
- config/webhook/service.yaml
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
part of https://github.com/openkruise/kruise-game/issues/220
Support for cert-manager with CA injection
Change the self-generated certificate to an option, defaulting to true. To adapt the chart changes, the webhook name is hard-coded
link PR: https://github.com/openkruise/charts/pull/146
> feat: add enable-cert-generation option

- pkg/controllers/gameserverset/gameserverset_controller_test.go
**What this PR does and why:**
The test coverage for the `GameServerSet` controller was at **54.6%**, and more importantly, core functions like the main `Reconcile` loop and `SyncStatus` had **zero** test coverage. This made refactoring risky and could let bugs slip through, especially in complex scaling or pod state scenarios.
This PR adds a comprehensive suite of unit tests using standard table-driven patterns and a fake client, bringing the package's coverage up from **54.6% to 73.0%**. No production code was changed.
Related Issue: https://github.com/openkruise/kruise-game/issues/266
**Key areas covered:**
*   **Reconciliation Loop (`Reconcile`):** Added tests for the main reconciliation flow, covering the creation of the backing `AdvancedStatefulSet` (ASTS) and handling of …
> [DRAFT LFX] Enhance GameServerSet Unit Test Coverage

- pkg/controllers/controller_test.go
This PR adds unit tests for the SetupWithManager function in `pkg/controllers/controller.go.`
The goal is to improve test coverage and ensure the setup logic—especially controller registration and field indexing—is tested and robust. This contributes to overall project stability as part of the effort described in issue #266 
The controller.go file had 0% test coverage previously.
As part of improving test coverage across the project (#266), it’s important to include even foundational logic like the controller setup.
> Add unit tests for `SetupWithManager` in `controller.go`

- apis/v1alpha1/gameserver_types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- docs/en/user_manuals/CRD_field_description.md
- docs/中文/用户手册/CRD字段说明.md
- pkg/controllers/gameserver/gameserver_controller_test.go
- pkg/controllers/gameserver/gameserver_manager.go
- pkg/controllers/gameserver/gameserver_manager_test.go
- pkg/util/client/no_deepcopy_lister.go
- pkg/util/gameserver.go
- pkg/util/gameserver_test.go
- test/e2e/client/client.go
- test/e2e/framework/framework.go
- test/e2e/testcase/testcase.go
I observed flaky e2e tests where `GameServer.spec` fields set by the tests (e.g., `opsState`, `deletionPriority`) reverted shortly after being written. Audit logs (In experimental branch, will be implemented in future PRs) showed values switching from the desired state back to old ones (e.g., `100 → 0`).
Solves: https://github.com/openkruise/kruise-game/issues/281
In the Pod → GameServer sync, any drift in `spec` or metadata triggered a **MergePatch** of the *entire* spec. If the reconcile loop used a stale cached GameServer, the patch carried outdated values and silently overwrote newer writes (“last writer wins”).
* **Minimal per-field patch for `spec`:**
* Include **only** `opsState`, `updatePriority`, `deletionPriority`, and `networkDisabled` when they truly change.
* Include metadata …
> fix(gameserver): patch spec minimally to avoid stale overwrite races
