.license/README.md
.license/dependency_decisions.yml

Signed-off-by: ChrisLiu <chrisliu1995@163.com>

update license checker

---

.github/workflows/ci.yaml
Makefile
hack/gencerts.sh

Workflow checker

---

.github/workflows/e2e-1.24.yaml
Makefile
scripts/deploy_kind.sh
test/e2e/framework/framework.go
test/kind-conf.yaml

Signed-off-by: ChrisLiu <chrisliu1995@163.com>

Add e2e test checker

---

docs/中文/用户手册/容器启动顺序控制.md
docs/中文/用户手册/自定义服务质量.md

Signed-off-by: ChrisLiu <chrisliu1995@163.com>

add doc for Container Launch Priority

---

docs/en/user_manuals/network.md
docs/中文/最佳实践/PvE类型游戏部署实践.md
docs/中文/最佳实践/PvP类型游戏部署实践.md
docs/中文/用户手册/网络模型.md

Signed-off-by: ChrisLiu <chrisliu1995@163.com>

update docs: rename HostPort to Kubernetes-HostPort

---

.github/workflows/ci.yaml
.github/workflows/e2e-1.24.yaml
apis/v1alpha1/gameserver_types.go
apis/v1alpha1/gameserverset_types.go
config/crd/bases/game.kruise.io_gameservers.yaml
config/crd/bases/game.kruise.io_gameserversets.yaml

https://github.com/openkruise/kruise-game/issues/47

add print columns for GameServerSet and GameServer

---

cloudprovider/kubernetes/hostPort.go

https://github.com/openkruise/kruise-game/issues/77

improve hostport cache to record allocated ports of pod

---

pkg/controllers/gameserver/gameserver_manager.go

https://github.com/openkruise/kruise-game/issues/78

correct gs network status when pod network status is nil

---

apis/v1alpha1/gameserverset_types.go
pkg/controllers/gameserver/gameserver_controller.go
pkg/controllers/gameserver/gameserver_manager.go
pkg/util/gameserver.go
pkg/util/gameserver_test.go
pkg/util/hash_test.go

https://github.com/openkruise/kruise-game/issues/83

support to sync gs metadata from from gsTemplate

---

apis/v1alpha1/gameserver_types.go
pkg/controllers/gameserverset/gameserverset_controller.go
pkg/controllers/gameserverset/gameserverset_manager.go
pkg/controllers/gameserverset/gameserverset_manager_test.go
pkg/util/gameserver.go
pkg/util/gameserver_test.go

https://github.com/openkruise/kruise-game/issues/76

feat: add new opsState type named Kill

---

docs/中文/最佳实践/PvP类型游戏部署实践.md

add "apiVersion: game.kruise.io/v1alpha1"

add "apiVersion: game.kruise.io/v1alpha1"

---

Makefile
cloudprovider/alibabacloud/nlb.go
cloudprovider/alibabacloud/nlb_sp.go
cloudprovider/alibabacloud/nlb_sp_test.go
cloudprovider/alibabacloud/nlb_test.go
cloudprovider/options/alibabacloud_options.go
config/manager/config.toml

https://github.com/openkruise/kruise-game/issues/134

feat: add AlibabaCloud-NLB network plugin

---

CHANGELOG.md

add v0.8.0 changelog

---

CHANGELOG.md

add changelog in v0.8.0

---

pkg/controllers/gameserverset/gameserverset_controller_test.go
pkg/controllers/gameserverset/gameserverset_manager.go
pkg/controllers/gameserverset/gameserverset_manager_test.go

https://github.com/openkruise/kruise-game/issues/170

reconstruct the logic of GameServers scaling

---

cloudprovider/options/volcenginecloud_options.go
cloudprovider/volcengine/clb.go
cloudprovider/volcengine/clb_test.go
config/manager/config.toml

fix:add block port in volc engine

---

cloudprovider/alibabacloud/slb.go
cloudprovider/alibabacloud/slb_test.go
docs/en/user_manuals/network.md
docs/中文/用户手册/网络模型.md
test/e2e/framework/framework.go

To Keep Source IP , Local external traffic type should be support !!

add support svc external traffic policy for alibabacloud slb

---

cloudprovider/config.go
cloudprovider/hwcloud/elb.go
cloudprovider/hwcloud/hwcloud.go
cloudprovider/manager/provider_manager.go
cloudprovider/options/hwcloud_options.go
config/manager/config.toml
docs/en/user_manuals/network.md
docs/中文/用户手册/网络模型.md

add hwcloud elb plugin work with ccm (https://github.com/kubernetes-sigs/cloud-provider-huaweicloud/tree/master) like aliyun slb

Add hwcloud provider and elb plugin

---

config/scheduler/index-offset-scheduler.yaml
config/scheduler/kustomization.yaml

scheduler repo: https://github.com/CloudNativeGame/index-offset-scheduler

Add index-offset-scheduler

---

.gitignore
cloudprovider/volcengine/eip.go
cloudprovider/volcengine/eip_test.go
go.mod

feat(cloud_provider): add eip provider of VKE

---

cloudprovider/alibabacloud/slb_sp.go
cloudprovider/alibabacloud/slb_sp_test.go

https://github.com/openkruise/kruise-game/issues/223

enhance: AlibabaCloud-SLB-SharedPort plugin support managed services

---

cloudprovider/kubernetes/hostPort.go

让Kubernetes-HostPort 支持 TCPUDP 协议，当协议为 TCPUDP 时，给 container 写入的是 2 个端口号相同的 HostPort，协议分别为 TCP 和 UDP。
场景：应用同时监听某个端口的 TCP 和 UDP 协议，且希望对外也能用相同的端口号暴露。
比如游戏客户端与服务端主要用 UDP 协议通信，但某些玩家网络环境可能用不了 UDP，游戏客户端自动 fallback 到同端口的 TCP 协议。
对标 Agones 的 TCPUDP(https://github.com/googleforgames/agones/issues/1523) ，有了此功能后，还可实现用负载均衡器的端口段监听器+HostPort 来实现大规模的端口映射：
https://www.bilibili.com/video/BV1odMkzWEDu?vd_source=aec72c2053794e8a3e75e07931c8b440&spm_id_from=333.788.videopod.sections

feat(Kubernetes-HostPort): support TCPUDP protocol

---

cloudprovider/volcengine/clb.go
cloudprovider/volcengine/clb_test.go

feat: 支持多 ingress IP 模式，新增配置项 EnableMultiIngress

---

cloudprovider/hwcloud/eip_cce.go
cloudprovider/hwcloud/eip_cce_test.go
cloudprovider/hwcloud/elb_cce.go
cloudprovider/hwcloud/elb_cce_test.go
cloudprovider/hwcloud/elb_test_mock.go
cloudprovider/hwcloud/hwcloud.go
cloudprovider/options/hwcloud_options.go
config/manager/config.toml
docs/en/user_manuals/network.md
docs/中文/用户手册/网络模型.md
go.mod
go.sum

support all annotations of ELB in this doc: https://support.huaweicloud.com/usermanual-cce/cce_10_0014.html
only support HuaweiCloud's `CCE Turbo` cluster in this doc: https://support.huaweicloud.com/usermanual-cce/cce_10_0651.html
docs: https://support.huaweicloud.com/usermanual-cce/cce_10_0897.html

add huawei cloud EIP support, enhanced support for ELB

---

.github/workflows/e2e-1.30.yaml
config/manager/manager.yaml
config/manager/patches/add-leader-elect-patch.yaml
main.go
pkg/webhook/server.go
pkg/webhook/server_test.go
scripts/deploy_kind.sh

part of https://github.com/openkruise/kruise-game/issues/220
To avoid state inconsistency issues by enable leader election in high-availability deployment modes with multiple replicas 
Requires further testing. Any suggestions are welcome

feat: enable leader election
